version: 2
updates:
  - package-ecosystem: "npm" # 
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      production-deps:
        dependency-type: "production"
      development-deps:
        dependency-type: "development"
